spring:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/spring_batch
    username: root
    password: Abhishek@1009
  university:
    datasource:
      jdbc-url: jdbc:mysql://localhost:3306/university
      username: root
      password: Abhishek@1009
  batch:
    jdbc:
      initialize-schema: always