apiVersion: batch/v1
kind: Job
metadata:
  name: random-error-job
  labels:
    name: random-error-job
spec:
  completions: 3
  parallelism: 3
  template:
    spec:
      containers:
      - name: random-error-job
        image: kodekloud/random-error
      restartPolicy: Never