apiVersion: v1
kind: LimitRange
metadata:
  name: mem-limit-range
  namespace: dev
spec:
  limits:
  - default:
      memory: "512Mi"   # cpu usage
    defaultRequest:
      memory: "256Mi"   #Memory usage
    type: Container